-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 11:56:56 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema labplan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `labplan` ;

-- -----------------------------------------------------
-- Schema labplan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labplan` DEFAULT CHARACTER SET utf8 ;
USE `labplan` ;

-- -----------------------------------------------------
-- Table `labplan`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labplan`.`patients` (
  `patient_id` INT NOT NULL,
  `first_name` VARCHAR(75) NULL,
  `last_name` VARCHAR(75) NULL,
  `age` INT NULL,
  `height` INT NULL,
  `weight` INT NULL,
  PRIMARY KEY (`patient_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labplan`.`lab_tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labplan`.`lab_tests` (
  `test_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NULL,
  `value_min` FLOAT NULL,
  `value_max` FLOAT NULL,
  PRIMARY KEY (`test_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labplan`.`lab_lists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labplan`.`lab_lists` (
  `panel_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `creation_date` DATETIME NULL,
  PRIMARY KEY (`panel_id`),
  INDEX `fk_lab_test_panel_patients1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_lab_test_panel_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `labplan`.`patients` (`patient_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labplan`.`lab_results`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `labplan`.`lab_results` (
  `test_id` INT NOT NULL,
  `list_id` INT NOT NULL,
  `value` FLOAT NULL,
  INDEX `fk_lab_result_lab_test1_idx` (`test_id` ASC),
  INDEX `fk_lab_result_lab_test_panel1_idx` (`list_id` ASC),
  PRIMARY KEY (`test_id`, `list_id`),
  CONSTRAINT `fk_lab_result_lab_test1`
    FOREIGN KEY (`test_id`)
    REFERENCES `labplan`.`lab_tests` (`test_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lab_result_lab_test_panel1`
    FOREIGN KEY (`list_id`)
    REFERENCES `labplan`.`lab_lists` (`panel_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
