/*
-- Query: SELECT * FROM labplan_production.lab_tests
LIMIT 0, 1000

-- Date: 2017-12-19 23:42
*/
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (2,'ACTH Suppression','The overnight dexamethasone suppression test checks to see how taking a steroid medicine called dexamethasone changes the levels of the hormone cortisol in the blood. This test checks for a condition in which large amounts of cortisol are produced by the adrenal glands (Cushing\'s syndrome).',16,24);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (3,'Adrenocorticotropic Hormone (ACTH)','An adrenocorticotropic hormone test measures the level of adrenocorticotropic hormone (ACTH) in the blood to check for problems with the pituitary gland and adrenal glands.',62,86);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (4,'Alanine Aminotransferase (ALT)','An alanine aminotransferase (ALT) test measures the amount of this enzyme in the blood. ALT is found mainly in the liver, but also in smaller amounts in the kidneys, heart, muscles, and pancreas. ALT was formerly called serum glutamic pyruvic transaminase (SGPT).',6,12);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (5,'Albumin','A total serum protein test measures the total amount of protein in the blood. It also measures the amounts of two major groups of proteins in the blood: albumin and globulin.',8.6,12.4);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (6,'Alkaline Phosphatase','An alkaline phosphatase (ALP) test measures the amount of the enzyme ALP in the blood. ALP is made mostly in the liver and in bone with some made in the intestines and kidneys. It also is made by the placenta of a pregnant woman.',29.4,32.6);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (7,'Allergy Tests','Allergy testing involves having a skin or blood test to find out what substance, or allergen, may trigger an allergic response in a person. Skin tests are usually done because they are rapid, reliable, and generally less expensive than blood tests, but either type of test may be used.',0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (8,'Alpha-Fetoprotein (AFP)','An alpha-fetoprotein (AFP) blood test checks the level of AFP in a pregnant woman\'s blood. AFP is a substance made in the liver of an unborn baby (fetus). The amount of AFP in the blood of a pregnant woman can help see whether the baby may have such problems as spina bifida and anencephaly. An AFP test can also be done as part of a screening test to find other chromosomal problems, such as Down syndrome (trisomy 21) or Edwards syndrome (trisomy 18). An AFP test can help find an omphalocele, a congenital problem in which some of the baby\'s intestines stick out through the belly wall.',2.5,8);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (9,'Amylase','An amylase test measures the amount of this enzyme in a sample of blood taken from a vein or in a sample of urine.',3.6,9.6);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (10,'Antibody Tests (Coombs Test)','Coombs tests are done to find certain antibodies that attack red blood cells. Antibodies are proteins made by the immune system. Normally, antibodies bind to foreign substances, such as bacteria and viruses, and cause them to be destroyed.',9.5,12.5);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (11,'Antinuclear Antibodies (ANA)','An antinuclear antibody (ANA) test measures the amount and pattern of antibodies in your blood that work against your own body (autoimmune reaction).',6.32,8.66);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (12,'Aspartate Aminotransferase (AST)','An aspartate aminotransferase (AST) test measures the amount of this enzyme in the blood. AST is normally found in red blood cells, liver, heart, muscle tissue, pancreas, and kidneys. AST formerly was called serum glutamic oxaloacetic transaminase (SGOT).',9.9,12.6);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (13,'Bicarbonate (Carbon Dioxide)',NULL,0.1,2.5);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (14,'Bilirubin','A bilirubin test measures the amount of bilirubin in a blood sample. Bilirubin is a brownish yellow substance found in bile. It is produced when the liver breaks down old red blood cells. Bilirubin is then removed from the body through the stool (feces) and gives stool its normal color.',3,8);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (15,'Blood Culture','The blood does not normally have any bacteria or fungi in it. A blood culture is a test of a blood sample to find germs (such as bacteria or a fungus) that can cause an infection.',0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (16,'Blood Glucose',NULL,2.6,10);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (17,'Blood Type','Blood type tests are done before a person gets a blood transfusion and to check a pregnant woman\'s blood type. Human blood is typed by certain markers (called antigens) on the surface of red blood cells. Blood type may also be done to see if two people are likely to be blood relatives.',0,4);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (18,'Blood Urea Nitrogen (BUN)','A blood urea nitrogen (BUN) test measures the amount of nitrogen in your blood that comes from the waste product urea. Urea is made when protein is broken down in your body. Urea is made in the liver and passed out of your body in the urine.',0.5,2.6);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (19,'Breast Cancer (BRCA) Gene','A breast cancer (BRCA) gene test is a blood test to check for changes (mutations) in genes called BRCA1 and BRCA2. This test can help you know your chance of getting breast cancer and ovarian cancer. A BRCA gene test does not test for cancer itself. ',0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (20,'Dexamethasone Suppression Test ',NULL,36,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (21,'Electrolyte Panel',NULL,2.5,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (22,'Estrogens',NULL,4.8,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (23,'Folic Acid',NULL,3.6,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (24,'Follicle-Stimulating Hormone',NULL,1.65,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (25,'Globulin',NULL,36.4,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (26,'Glucose',NULL,24.2,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (27,'Glycohemoglobin (HbA1c, A1c)',NULL,16.5,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (28,'Gonorrhea',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (29,'Growth Hormone ',NULL,44.2,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (30,'HDL Cholesterol',NULL,21,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (31,'Helicobacter pylori ',NULL,36,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (32,'Hepatitis Panel',NULL,43,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (33,'Homocysteine',NULL,64,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (34,'Human Chorionic Gonadotropin (hCG)',NULL,23,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (35,'Human Immunodeficiency Virus (HIV)',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (36,'Iron (Fe)',NULL,53,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (37,'Ketones',NULL,123,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (38,'Lactic Acid Dehydrogenase (LDH)',NULL,11,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (39,'LDL Cholesterol',NULL,25.4,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (40,'Lead (Pb)',NULL,36.1,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (41,'Liver Function Panel',NULL,62.1,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (42,'Magnesium (Mg)',NULL,33,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (43,'Microalbumin Urine Test',NULL,12.2,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (44,'Mononucleosis',NULL,15,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (45,'Oral Glucose Tolerance Test',NULL,73,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (46,'Parathyroid Hormone (PTH)',NULL,12,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (47,'Partial Thromboplastin Time',NULL,16,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (48,'Phosphate (Phosphorus)',NULL,36,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (49,'Potassium (K) in Blood',NULL,22,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (50,'Potassium (K) in Urine',NULL,74,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (51,'Pregnancy Test ',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (52,'Progesterone',NULL,12,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (53,'Prolactin',NULL,33.1,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (54,'Prostate-Specific Antigen (PSA) ',NULL,2,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (55,'Prothrombin Time ',NULL,23.12,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (56,'Reticulocyte Count',NULL,5,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (57,'Rheumatoid Factor (RF)',NULL,0,NULL);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (58,'Rubella',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (59,'Sedimentation Rate',NULL,36,96);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (60,'Sickle Cell Test',NULL,22,44);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (61,'Sodium (Na)',NULL,10,100);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (62,'Stool Analysis',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (63,'Stool Analysis for Giardiasis (Ova and Parasite Test) ',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (64,'Stool Antigen Test ',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (65,'Stool Culture',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (66,'Syphilis ','',0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (67,'Testosterone',NULL,25,100);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (68,'Thyroid Hormone',NULL,36,44);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (69,'Thyroid-Stimulating Hormone (TSH)',NULL,1.25,9.25);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (70,'Total Serum Protein',NULL,200,400);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (71,'Uric Acid',NULL,2,2.9);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (72,'Urine Test',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (73,'Viral Tests',NULL,0,0);
INSERT INTO `lab_tests` (`test_id`,`name`,`description`,`value_min`,`value_max`) VALUES (74,'Vitamin B12',NULL,100,300);
